### ISSUE TITLE
Update which Docker container can be used?

### ISSUE THREAD

**Issue by blipp** [project-everest/project-everest.github.io#11]
The [website](https://project-everest.github.io/) currently recommends

> For the lazy: Docker

> Every night, we automatically build the projecteverest/everest Docker image with everything already built and verified, for you to directly pull from the Docker Hub. If you have Docker installed on your machine, then you can pull the image using the usual command:

> `docker pull projecteverest/everest-windows-nt`

However, [this particular container](https://hub.docker.com/r/projecteverest/everest-windows-nt/tags?page=1&ordering=last_updated) was last updated 8 months ago.

Instead, I tried [everest-linux](https://hub.docker.com/r/projecteverest/everest-linux) but it does not seem to have “everything already built”, at least there was no `FStar/bin/fstar.exe` in the container. Is this intentional, i.e., should the wording “everything already built and verified” be updated?

**Comment by tahina-pro** [comment]
The Everest-Windows container is no longer up-to-date, since our internal CI stopped working due to moby/moby#41058

If the Everest-Linux container that you picked contains no binaries, then this is a bug in our CI system that sometimes unnecessarily pushes and overwrites existing images. We will look into that.

Thank you for reporting!

**Comment by tahina-pro** [comment]
I just fixed the CI system accordingly, so from now on all Everest Linux Docker images should be fully built. Please ping again if not.

It now remains to change the documentation to explicitly state that, for now, the Everest Windows Docker images are stale because Cygwin is currently not as well supported within a Docker image as it used to be prior to June 1st, 2020.

**Comment by tahina-pro** [comment]
@nikswamy just uploaded an updated home page (94721849f99c79e461357e82d7ff75d5aa61411f), which incorporates changes from b73633ee2a44cec1432fdc0b1647efb86235bb6d and 0af8cb83aed5cce6c2b1c243c82397126447f0bd updating the documentation on Linux and Windows Docker images accordingly.
